# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('nickname', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=45)),
                ('password', models.CharField(max_length=32)),
                ('style', models.UUIDField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
            ],
        ),
    ]
