# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160918_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts2',
            new_name='Account',
        ),
    ]
