# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160918_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='style',
        ),
    ]
