# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_account_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='style',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
