# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_account_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='style',
            new_name='type',
        ),
    ]
